import React, { useEffect, useRef } from "react";

const services = [
  {
    id: 1,
    title: "Collection of Biowaste",
    subtitle:
      "Biowaste generated from kitchens, food industries, and agricultural operations forms a major portion of organic waste that must be managed responsibly. At EcoSphere, we use an advanced biological process powered by Black Soldier Fly (BSF) larvae to convert this waste into high-value resources.The larvae rapidly consume organic waste, reducing its volume while producing nutrient-rich by-products such as protein meal and organic compost. This creates a closed-loop, environmentally friendly system where waste is diverted from landfills and transformed into valuable materials — enabling efficient, sustainable, and scientific biowaste management.",
    img: "/service1.png",
    points: ["Real-Time Tracking", "Certified Process", "Full Documentation"],
  },
  {
    id: 2,
    title:
      "Upcycling Process by BSF Bioconversion of Biowaste for Environmental Value",
    subtitle:
      "Rather than allowing biowaste to accumulate in landfills and harm the environment, our system uses Black Soldier Fly (BSF) larvae as a natural and highly efficient bioconversion engine. These larvae rapidly break down organic waste in a controlled, scientific process, reducing pollution and diverting waste from landfills.Through this upcycling method, biowaste is transformed into high-value outputs such as protein-rich insect meal, organic fertilizer, and soil enhancers. This eco-friendly process restores environmental balance while ensuring that every kilogram of biowaste is converted into something valuable and sustainable.",
    img: "/service2.png",
    points: [""],
  },
  {
    id: 3,
    title:
      "Organic Compost Rejuvenate the Soil to Support the Ecosystem",
    subtitle:
      "The compost produced from our BSF process contains nutrient-rich by-products, including frass, a natural organic material generated by the larvae. Frass is loaded with beneficial microorganisms, essential nutrients, and organic matter that help restore soil health.When applied to fields, gardens, or agricultural land, this compost improves soil structure, boosts fertility, and enhances its ability to retain moisture. By returning these natural nutrients to the earth, we rejuvenate the soil and support a healthier, more resilient ecosystem — enabling plants to grow stronger, naturally and sustainably.",
    img: "/service3.png",
    points: ["Real-Time Tracking", "Certified Process", "Full Documentation"],
  },
  {
    id: 4,
    title:
      "Sustainable Insect Protein Nourishing Animals Naturally, Sustainably, and Responsibly",
    subtitle:
      "Black Soldier Fly (BSF) larvae are naturally rich in high-quality protein, essential amino acids, and vital nutrients that pets and livestock instinctively thrive on. This makes BSF-based protein an ideal, biologically appropriate food source for animals.At Fabbco, our insect-protein products support animal health while advancing our commitment to environmental responsibility. By choosing sustainable insect protein, we reduce the pressure on traditional feed resources, lower the environmental footprint, and contribute to a more resilient planet.",
    img: "/service4.png",
    points: ["Real-Time Tracking", "Certified Process", "Full Documentation"],
  },
];

const ServicesGrid = () => {
  const sectionRefs = useRef([]);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add("animate-show");
          }
        });
      },
      { threshold: 0.3 }
    );

    sectionRefs.current.forEach((ref) => {
      if (ref) observer.observe(ref);
    });
  }, []);

  return (
    <section className="-mt-24 w-full bg-black py-20 md:py-24 lg:py-32 px-4 md:px-6">
      <div className="max-w-6xl mx-auto">
        {/* <div className="text-center mb-28 -mt-20">
          <h2 className="text-3xl md:text-4xl font-extrabold text-white tracking-tight">
            Our Scientific Waste-to-Value Process
          </h2>
        </div> */}
          {services.map((service, idx) => {
          const isReversed = idx % 2 === 1;

          return (
            <article
              key={service.id}
              ref={(el) => (sectionRefs.current[idx] = el)}
              className={`-mt-20 opacity-0 translate-y-10 transition-all duration-[1200ms] ease-out grid grid-cols-1 lg:grid-cols-2 gap-6 lg:gap-12 mb-16 lg:mb-24 items-center ${
                isReversed
                  ? "lg:grid-cols-[1.1fr_1fr]"
                  : "lg:grid-cols-[1fr_1.1fr]"
              }`}
            >
              {/* IMAGE --------------- */}
              <div
                className={`${
                  isReversed
                    ? "lg:order-2 slide-in-right"
                    : "lg:order-1 slide-in-left"
                }`}
              >
                <div className="relative rounded-xl overflow-hidden shadow-[0_10px_32px_rgba(0,0,0,0.1)]">
                  <img
                    src={service.img}
                    alt={service.title}
                    className="w-full h-96 lg:h-[440px] object-cover transition-transform duration-300 hover:scale-[1.02]"
                  />
                </div>
              </div>

              {/* CONTENT ---------------- */}
              <div
                className={`${
                  isReversed ? "lg:order-1" : "lg:order-2"
                } px-1 relative fade-in`}
              >
                {/* STEP DESIGN */}
                <div className="relative mb-8">
                  <div className="text-[110px] font-extrabold text-emerald-100/20 leading-none">
                    {String(service.id).padStart(2, "0")}
                  </div>

                  <div className="absolute inset-0 flex items-center pl-1">
                    <span className="tracking-[0.3em] text-emerald-300 text-[18px] font-medium">
                      STEP {service.id}
                    </span>
                  </div>
                </div>

                {/* HEADING */}
                <h3 className="text-2xl -mt-6 lg:text-3xl font-extrabold text-white mb-3">
                  {service.title}
                </h3>

                {/* GREEN UNDERLINE */}
                <div className="w-16 h-[4px] bg-emerald-400 mb-5"></div>

                {/* SUBTITLE */}
                <p className="text-base text-white leading-relaxed mb-5">
                  {service.subtitle}
                </p>

                {/* POINTS – Show only for ID 1 */}
                {service.id === 1 && (
                  <ul className="flex flex-wrap gap-2">
                    {service.points.map((point, i) => (
                      <li
                        key={i}
                        className="flex items-center gap-2 bg-emerald-50 text-emerald-900 px-4 py-2 rounded-full text-sm border border-emerald-200 hover:bg-emerald-100 transition-all shadow-sm"
                      >
                        <svg
                          width="12"
                          height="12"
                          viewBox="0 0 24 24"
                          fill="none"
                        >
                          <path
                            d="M20 6L9 17L4 12"
                            stroke="#059669"
                            strokeWidth="2"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                          />
                        </svg>
                        <span>{point}</span>
                      </li>
                    ))}
                  </ul>
                )}

              </div>
            </article>
          );
        })}
      </div>
    </section>
  );
};

export default ServicesGrid;
